CREATE TABLE `financialCalculations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`evaluationId` int NOT NULL,
	`estimatedPrice` int NOT NULL,
	`grossMarginRate` decimal(5,2) NOT NULL,
	`monthlyRent` int NOT NULL,
	`monthlyLabor` int NOT NULL,
	`otherCosts` int DEFAULT 0,
	`seats` int NOT NULL,
	`dailyBreakEven` decimal(12,2),
	`dailyTurnover` decimal(5,2),
	`industryAvgTurnover` decimal(5,2),
	`riskLevel` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `financialCalculations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `restaurants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` varchar(64) NOT NULL,
	`priceRangeMin` int NOT NULL,
	`priceRangeMax` int NOT NULL,
	`targetCustomer` varchar(64) NOT NULL,
	`scale` varchar(64) NOT NULL,
	`businessModel` varchar(64) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `restaurants_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scoringConfigs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(128) NOT NULL,
	`businessModel` varchar(64) NOT NULL,
	`trafficWeight` int NOT NULL DEFAULT 20,
	`locationWeight` int NOT NULL DEFAULT 20,
	`customerMatchWeight` int NOT NULL DEFAULT 20,
	`heatWeight` int NOT NULL DEFAULT 15,
	`costWeight` int NOT NULL DEFAULT 15,
	`competitionWeight` int NOT NULL DEFAULT 10,
	`isDefault` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scoringConfigs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `siteEvaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`restaurantId` int NOT NULL,
	`address` text NOT NULL,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`area` int NOT NULL,
	`monthlyRent` int NOT NULL,
	`occupancyMorning` int,
	`occupancyNoon` int,
	`occupancyEvening` int,
	`isMainCorridor` int DEFAULT 0,
	`storefrontWidth` decimal(5,2),
	`hasStairs` int DEFAULT 0,
	`hasDeepAlley` int DEFAULT 0,
	`surroundingDesc` text,
	`population1km` int,
	`population3km` int,
	`officeBuildings` int,
	`estimatedWorkstations` int,
	`parkingSpots` int,
	`ageGroup` varchar(64),
	`consumptionLevel` varchar(64),
	`trafficScore` int,
	`locationScore` int,
	`customerMatchScore` int,
	`heatScore` int,
	`costScore` int,
	`competitionScore` int,
	`totalScore` decimal(5,2),
	`recommendation` varchar(32),
	`llmAnalysis` text,
	`breakEvenRevenue` decimal(12,2),
	`breakEvenTurnover` decimal(5,2),
	`financialRisk` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `siteEvaluations_id` PRIMARY KEY(`id`)
);
